apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: local-service2-service-destination
spec:
  host: local-service2-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: local-service2-service-route
spec:
  hosts:
    - local-service2-service
  http:
    - route:
      - destination:
          host: local-service2-service
          subset: v2
        weight: 80
      - destination:
          host: local-service2-service
          subset: v1
        weight: 20
      retries:
        attempts: 3
        perTryTimeout: 1s
        retryOn: 5xx
      timeout: 3s
