---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Service1 Prometheus
      type: prometheus
      url: http://local-service1-service/metrics
      access: proxy
      isDefault: true
    - name: Service2 Prometheus
      type: prometheus
      url: http://local-service2-service/metrics
      access: proxy
      isDefault: true
